name: i18n-master-sync
on:
  push:
    branches:
      - main
    paths:
      - 'src/i18n-keysets/**'

jobs:
  i18n-master-sync:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload changes to Weblate
        uses: dgaponov/weblate-action@v1.7.0
        with:
            SERVER_URL: "http://158.160.122.254"
            TOKEN: ${{ secrets.WEBLATE_TOKEN }}
            PROJECT: "datalens"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
