name: i18n-check
on:
  # pull_request_target is needed instead of just pull_request
  # because secret is needed to sync with weblate
  # Attention! Read more at https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests
  pull_request_target:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  i18n-check-run:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - id: check_i18n_changed
        run: echo "::set-output name=i18n_changed::$(git diff --name-only origin/main..HEAD | grep 'src/i18n-keysets/')"

      - name: Verifying changes with Weblate
        if: steps.check_i18n_changed.outputs.i18n_changed != ''
        uses: dgaponov/weblate-action@v1.28
        with:
            SERVER_URL: "http://158.160.122.254"
            TOKEN: ${{ secrets.WEBLATE_TOKEN }}
            PROJECT: "datalens"
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
