name: i18n-check
on:
  pull_request:
    branches:
      main

jobs:
  i18n-check-run:
    runs-on: ubuntu-latest
    name: TEST
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check i18n
        uses: dgaponov/weblate-action@v1.7
        with:
            SERVER_URL: "http://158.160.122.254"
            TOKEN: ${{ secrets.WEBLATE_TOKEN }}
            PROJECT: "datalens"
