name: i18n-check
on:
    pull_request:
        branches:
            main

jobs:
  i18n-check-run:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: dgaponov/weblate-action@v1.2
        with:
            SERVER_URL: "http://158.160.122.254/api/"
            TOKEN: ${{ secrets.WEBLATE_TOKEN }}
            PROJECT: "datalens"
